### ISSUE TITLE
Suggested Enhancement: Guard.AgainstInvalidEnum

### ISSUE THREAD

**Issue by SeanKilleen** [liteguard/liteguard#108]
This one has saved me before and I'd love to contribute it to LiteGuard. (have code & tests already)

The general purpose: Throw if a given value can't be mapped to an Enum.

Usage: `Guard.AgainstInvalidEnum<MyEnum>(object objectToCheck)`

I have the code and tests to cover it in xUnit, but am not necessarily familiar with the xbehave style. 

Do you think this would be a worthwhile addition to this library? And if so, would xUnit tests be sufficient, or do you strongly prefer them to be written using xbehave? 

## Example:

```
public enum MyEnum
{
   ValueOne = 1,
   ValueTwo = 2
}

Guard.AgainstInvalidEnum<MyEnum>(MyEnum.ValueOne); // doesn't throw

var invalidEnum = (MyEnum) 3;

Guard.AgainstInvalidEnum<MyEnum>(invalidEnum); // throws
```

**Comment by adamralph** [comment]
Hi @SeanKilleen, I like this and I'd like to explore it. It fits in with LiteGuard's philosophy of making up for missing language features rather than encouraging people to business rules in the wrong places.

I'll come back with more thoughts ASAP.

Assigning to myself for now to remind me to chime in again.

**Comment by SeanKilleen** [comment]
@adamralph sounds good! Yeah, that's why I recommended it; I recently saw an enum that didn't have a value defined for 0 but was cast and passed through anyway (to the surprise of far too many people).  Seems like a defensive mechanism that a lot of developers forget about.

**Comment by adamralph** [comment]
@SeanKilleen what do you think about this for the signatures?

```C#
/// <exception cref="System.InvalidEnumArgumentException">
///     <paramref name="argument" /> is an invalid enum value.
/// </exception>
Guard.AgainstInvalidEnumArgument<TArgument>(
    string parameterName, TArgument argument)
    where TArgument : struct

/// <exception cref="System.ArgumentException">
///     <paramref name="argumentProperty" /> is an invalid enum value.
/// </exception>
Guard.AgainstInvalidEnumArgumentProperty<TProperty>(
    string parameterName, string propertyName, TProperty argumentProperty)
    where TProperty : struct
```

It's unfortunate that C# doesn't allow `enum` as a generic type constraint. If the generic type argument is not an enum, we can either skip the check or throw an exception. I'm not sure which is best.

**Comment by SeanKilleen** [comment]
@adamralph that makes sense to me. I'll throw together a Work in progress PR and we can see how it feels.

Last question: I'm not a familiar with xBehave but xUnit is totally

**Comment by adamralph** [comment]
@SeanKilleen that approach sounds fine, thanks!

What's your opinion on skip/throw when the type is not an enum?

**Comment by SeanKilleen** [comment]
@adamralph I'd say throw. If the user is asking if something is a valid enum, then to me we would want to throw if:

* Argument doesn't pass enum tryparse
* Argument doesn't pass enum.isdefined with the result of enum tryparse (which helps with numbers being passed as strings, etc. to convert them)

**Comment by adamralph** [comment]
Agreed. Let's throw.

It won't be possible to pass a `string` since it's not a struct, but we'll have to do some type inspection on `TArgument` and `TProperty` so see if they are enum types. I guess we should throw an `ArgumentException` in both cases.

**Comment by adamralph** [comment]
I've just thought of something else which the proposed signatures do not support:

```C#
public enum Color
{
    Red,
    Green,
    ....
}

public void Foo(MyEnum? color)
{
    Guard.AgainstInvalidEnum(color, "color");

   if (color.HasValue)
   {
    ....
}
```

What do we do here? I guess if the value is not null we run the check, if it is null, we skip it?

**Comment by SeanKilleen** [comment]
@adamralph yeah, agree. Would that follow the other code conventions and we'd build two new methods, adding `IfNullable` onto the end?

**Comment by adamralph** [comment]
Rather than `IfNullable`, it would be `IfEnum`, but perhaps this needs a little more thought...

**Comment by SeanKilleen** [comment]
Hmmm, yeah. After a little more consideration, I'm thinking these are the following user expectations:

* If I define an enum and want to see if a value is valid, I expect it not to be null (hence, we'd throw)
* If I define a nullable enum and I want to check if a value is valid, I allow that null could be a valid value. (hence, we'd skip on nullable).
* The outlier is that I have a nullable Enum type, but still want to check if the values are valid *despite* knowing that I allow nulls (e.g. consider no value to be invalid).

The first two cases make sense and I think are covered by our initial design. In the last one, I wonder if we're getting into business rule territory (something that I think you're looking to avoid on this). The code has explicitly defined that something is nullable, but we'd be ignoring that and throwing on null.

Thoughts?

**Comment by adamralph** [comment]
My current thinking is that these new methods should have one purpose alone: to restrict an enum argument to the range of values defined in the enum. I.e. a missing language feature.

I think there are only two use cases:

```C#
void Foo(MyEnum bar)
{
    Guard.AgainstInvalidEnumArgument("bar", bar);
}

void Foo(MyEnum? bar)
{
    Guard.AgainstInvalidEnumArgument("bar", bar);
}
``` 

The first case is clear, and is covered in our design. Here the value can never be null since the `Foo` signature already enforces that.

In the second case, would I ever want an exception to be throw if the value was null? I'm already saying that I accept nulls in my `Foo` signature. I just want to be sure that if the value is not null and I therefore I decide to use it, that it's a valid enum value. Alternatively, we could not support this at all and force the developer to write:

```C#
void Foo(MyEnum? bar)
{
    if (bar.HasValue)
    {
        Guard.AgainstInvalidEnumArgument("bar", bar.Value);
        ....
    }
}
```

But given that they're probably *always* going to write that, we may as well wrap it up for them in an overload.

**Comment by adamralph** [comment]
BTW, an old article but most, if not all of it, still applies - http://blogs.msdn.com/b/kcwalina/archive/2004/05/18/134208.aspx

It seems `Enum.IsDefined` is expensive.

**Comment by SeanKilleen** [comment]
@adamralph yeah, I'm aware of that. I'm not sure we can avoid it (it's still necessary to guard at some points), but maybe we include a note about that in the remarks? Or even in the description if we want to really make sure people know it?

**Comment by adamralph** [comment]
I'm beginning to worry that we will lead people down a worse path than

```C#
switch (foo)
{
    ...
    default:
        throw new InvalidEnumArgumentException(...);
}
```

**Comment by SeanKilleen** [comment]
@adamralph isn't that still not a recommended practice though? What happens when you add a new enum? You get a bunch of InvalidEnumArgumentExceptions at runtime (assuming you're not appropriately writing tests, but that's reality).

I'm wondering if we could take a slightly cheaper approach. We could load all the values of the enum, then iterate through them and do an equality comparison. `IsDefined` is expensive, but I don't see any such worries around `TryParse` (that i've found yet).

Maybe it's a question of what we define as a worse path. If someone needs to verify that a value is part of an enum, there only appears to be one way to truly do that, which is expensive. Anything else will get us close but no cigar.

Not to go throwing an option into the mix, but we could always set a flag, `useIsDefined`, and default it to true. Those who require greater performance could flip that to false an accept the consequences, and it should be easy to explain the purpose in the docs.

**Comment by adamralph** [comment]
Can you elaborate on the method you'd use involving loading all the values of the enum and using `TryParse`?

I'd also like to sound this out from another angle: when would you typically define an enum parameter and then not use it for a decision tree (`if`/`switch`)?

**Comment by SeanKilleen** [comment]
@adamralph was spitballing a bit but I was thinking that after we confirmed that something was an enum, we could do something along the lines of the following:

    var validValues = Enum.GetValues(typeof(T)).Cast<T>().ToList();

At this point, we'd conceivably have the valid values of that enum, so I wonder if we could then just return something like `return validValues.Any(x=> x == inputValue)`.

I'm sure there are probably some other concerns with this approach, but at first glance it seems worth considering.

**Comment by SeanKilleen** [comment]
@adamralph also, a fuzzy use case regarding when would you use it for other than an if/switch: in some cases I've seen ints that get mapped to enums before being stored in the database (accepted values, etc.) -- prior to sending to the DB, you might want to ensure that the values are acceptable.

**Comment by SeanKilleen** [comment]
Further pseudocode of what I'm thinking:

```
bool isTypeEnum = TEnumType.IsEnum;
bool isInputEnum = inputObject is Enum;

if (IsTypeEnum && IsInputEnum)
{
    var validValues = Enum.GetValues(typeof(TEnumType)).Cast<TEnumType>().ToList();
     return validValues.Any(x=> x == inputValue);
}
```

Can you poke some holes in that?

**Comment by SeanKilleen** [comment]
@adamralph Also, I think to check nullability, we can do something along the lines of:

````C#
if (TEnumType.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>))
```

But that's just from [poking around MSDN](https://msdn.microsoft.com/en-us/library/ms366789.aspx), and I'm not sure how expensive if is.

So the code would essentially be:

* If the type isn't an `enum`, throw (invalid use of guard clause)
* Determine whether it's nullable
* If it's not nullable, and the object is null, throw
* If the input object isn't an enum, throw
* if the input object cant be cast to the enum type, throw
* get the valid values
* if none of the valid values match the input object, throw.

Let me know your thoughts.

**Comment by adamralph** [comment]
@SeanKilleen sorry to have gone quiet on this thread.

I've re-read the discussion so far and I'm still wrestling with myself over whether this belongs in LiteGuard.

**Comment by SeanKilleen** [comment]
@adamralph not a problem at all, I appreciate the thorough consideration.

I'll try to summarize where it seems like we are on it -- let me know if you agree on the summary.

It seems to be a fit for the project conceptually, but with a number of implementation concerns.

Conceptually, ensuring that an enum value actually fits within that enum is (I think) a good fit for Liteguard. It's guarding to make sure that your code can safely assume that the enum is assigned correctly to avoid unexpected behavior.

**The concerns seem to be:**

* Performance concerns
 * I'm pretty sure we could figure out a reasonably performant way to implement it.
 * We could also document potential costs in the xmldocs if there end up being any
* Concerns about rules around nullable values and potentially complex implementation. 
 * We could always require a "NullabilityBehavior" enum of our own (e.g. throw on null vs not throw on null), and give that a default if we ever feel reasonably confident. This way the user would have to make an active choice.
* Concerns around whether it would be abused / lead devs down a wrong path (e.g. if enums are only used for switch satatements, should we really be checking with a guard clause?)
 * I think I demonstrated some use cases outside of the pure switch statements where this could be helpful. 

Given the information above, I think it makes sense to implement in the library, but also makes sense to spend some time wrestling with implementation details a bit more before moving on it.

**Comment by adamralph** [comment]
@SeanKilleen I'm not too concerned with implementation right now. My chief concern is whether this is really required.

I'd like to see a compelling example of where it would make sense to use this guard clause. I'm having a hard time buying the case of pre-validation before DB insertion. For me, the DB should really just be used for persistence and not the enforcement of invariants. I'd rather focus on the fact that the object has been allowed to get into an invalid state before an attempt at persistence.

**Comment by SeanKilleen** [comment]
@adamralph Totally understandable. I'm not 100% convinced myself, but I think a lot of the value in having a guard clause of this nature would be for dealing with non-ideal scenarios for people who still aren't building apps the right way.

For example, the reason I built my own guard clause for this purpose is that I work in a highly legacy environment sometimes, and occasionally data values will be introduced at the database level that the application would not anticipate. We have validation in place, but oftentimes I don't see any protection against a random int value being cast into an enum. This assumption can cause some pain, as I'm sure you can imagine. A lot of developers, I've found, don't understand the fact that an int can be case to an Enum even if it's an invalid value. There are assumptions around this, both in dealing with input data and prior to persistence, that are harmful. This guard clause was my way of ensuring that this one type of error didn't pollute code under my purview. 

Similarly, while I personally 100% agree that the DB should be used for persistence instead of invariants, I work with a giant SQL database touched by over 50 applications, all of which are pretty legacy in some way. It is currently the "source of truth". Stored procs are used as the primary drivers of data there still. It's one of those. As such, I have to protect myself against things that would likely not be an issue if I was coding things myself, or working with a smaller team or a team that performed code reviews and was on the same page with things.

Since I had to use it for myself, I figured it might make sense to add here. Though honestly, if it's only me that's interested in it, I wouldn't be at all offended to drop it and not worry about it. :smile: I tend to think that if you have this much hesitance around it, we should probably trust your gut and leave it out.

**Comment by adamralph** [comment]
@SeanKilleen after taking embarrassingly long to think this over and get round to replying, I think it is best to leave this out of LiteGuard.

I sympathise deeply with your "giant SQL database touched by over 50 applications" situation, having endured similar horrors during my career. I think that helpers, such as the guard clause you're proposing, for helping to deal with these kinds of systems are useful, but belong in other packages. Those packages should make it clear that they are an aid for getting out of a bad situation, and should eventually be removed, with their removal acting as a indicator that at least part of your work is done. Whilst this is probably a never-attainable goal in many of these situations, I do think it's useful as (possibly never reachable) target.

LiteGuard, on the other hand, is a package "to stay". I.e. it's something that is designed to be used strategically in an app which is written "the right way".

**Comment by SeanKilleen** [comment]
@adamralph totally fine -- that explanation makes a lot of sense to me. I voted with my feet on said previous company anyway ;) I think think issue serves as a nice clarifying point for the library -- e.g. supporting things done the right way rather than serving as a way for bad situations to save themselves. 

Regardless, appreciate your considering it and the detailed discussion!

**Comment by SeanKilleen** [comment]
@adamralph one distant idea --  In the future, it could potentially be a cool idea to use Roslyn code analyzers along with Liteguard. If someone used a guard that indicated a smell (such as the one I proposed), the library could help out while simultaneously warning users that they should fix this situation. But agree that it would shift the narrow focus of the library which may still not be in its best interest, now or in the future.

**Comment by adamralph** [comment]
@SeanKilleen the introduction of a code analyzer is definitely something I'd like to do. E.g. it can catch the case when someone uses the wrong argument name (although the chances of that should now be diminishing greatly since the introduction of `nameof()`).

As for warning about invalid enums, I do think that's useful, but again I think it's something for that separate "legacy app sanity harness" package.

Good on you for voting with your feet...
